name: Send Alumni Reminders

on:
  # Runs every Sunday at 9:00 UTC
  schedule:
    - cron: "0 9 * * 0"
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run send_reminders.js
        run: node send_reminders.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
